services:
  ingress:
    image: "traefik:v3.5"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80" # Expose default web address
      - "8080:8080" # Expose Traefik Admin UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  echo-service:
    build:
      context: ./src/echo-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echo-service.rule=Host(`api.localhost`)" # This is the configuration for how to route trafic
      - "traefik.http.routers.echo-service.entrypoints=web"
      - "traefik.http.services.echo-service.loadbalancer.server.port=8080"

  homepage:
    build:
      context: ./src/homepage
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`localhost`)" # This is the configuration for how to route trafic
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=80"

  # Link: https://hub.docker.com/_/postgres
  # PostgreSQL
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  # PostgreSQL Admin UI
  database-ui:
    image: adminer
    restart: always
    ports:
      - 8081:8080
